INSERT INTO app_user(username, password, role, first_name, last_name, email, salary, birthday, hireday, gender, project_id) VALUES ('employee', 'qwerty', 'EMPLOYEE', 'Evgeniy', 'Deyneka', 'deyneko55@gmail.com', 15000, '1992-12-26', '2016-02-02', 'MALE', 3);
INSERT INTO app_user(username, password, role, first_name, last_name, email, salary, birthday, hireday, gender) VALUES ('admin', 'qwerty', 'ADMIN', 'Roman', 'Andriyanov', 'randriyanov@gmail.com', 100000, '1985-10-14', '2012-05-12', 'MALE');
INSERT INTO app_user(username, password, role, first_name, last_name, email, salary, birthday, hireday, gender, managed_project_id) VALUES ('pmanager', 'qwerty', 'PM', 'Denis', 'Ruzhuh', 'ruzhuh@gmail.com', 70000, '1982-04-02', '2008-07-21', 'MALE', 3);
INSERT INTO app_user(username, password, role, first_name, last_name, email, salary, birthday, hireday, gender, project_id) VALUES ('customer', 'qwerty', 'CUSTOMER', 'Elon', 'Mask', 'elon@tesla.com', 1000000, '1971-08-28', '1996-03-11', 'MALE', 3);

INSERT INTO app_user (username, password, first_name, last_name, birthday, hireday, salary, role, email, gender, managed_project_id) VALUES ('gcampbell3', 'test', 'Gloria', 'Campbell', '1979/05/05', '2006/08/27', 48370, 'PM', 'gcampbell13@domainmarket.com', 'FEMALE', 1);
insert into app_user (username, password, first_name, last_name, birthday, hireday, salary, role, email, gender, project_id) values ('mholmes4', 'xIPsICnk', 'Matthew', 'Holmes', '1983/12/22', '2012/02/18', 54643, 'EMPLOYEE', 'mholmes4@merriam-webster.com', 'MALE', 1);
insert into app_user (username, password, first_name, last_name, birthday, hireday, salary, role, email, gender, project_id) values ('rgrant0', '96ZnqN', 'Randy', 'Grant', '1991/08/01', '2013/02/04', 86500, 'EMPLOYEE', 'rgrant0@networksolutions.com', 'MALE', 1);
insert into app_user (username, password, first_name, last_name, birthday, hireday, salary, role, email, gender, project_id) values ('bmatthews1', '96ZnqN', 'Bobby', 'Matthews', '1985/05/12', '2013/02/04', 86500, 'EMPLOYEE', 'bmatthews1@dedecms.com', 'MALE', 1);
insert into app_user (username, password, first_name, last_name, birthday, hireday, salary, role, email, gender, project_id) values ('fbowman5', '96ZnqN', 'Eric', 'Porter', '1989/04/14', '2013/02/04', 86500, 'EMPLOYEE', 'eporter3@cisco.com', 'MALE', 1);

INSERT INTO app_user (username, password, first_name, last_name, birthday, hireday, salary, role, email, gender, managed_project_id) VALUES ('sfowler1', 'IFaum3Gu0Y', 'Sarah', 'Fowler', '1979/11/04', '2011/07/26', 23978, 'PM', 'sfowler1@google.pl', 'MALE', 2);
insert into app_user (username, password, first_name, last_name, birthday, hireday, salary, role, email, gender, project_id) values ('kbanks6', 'MlHktd', 'Katherine', 'Banks', '1975/05/15', '2009/01/30', 80332, 'EMPLOYEE', 'kbanks6@netlog.com', 'FEMALE', 2);
insert into app_user (username, password, first_name, last_name, birthday, hireday, salary, role, email, gender, project_id) values ('rporter7', 'Ixa0wcb64', 'Richard', 'Porter', '1978/01/18', '2010/06/09', 20589, 'EMPLOYEE', 'rporter7@cornell.edu', 'FEMALE', 2);
insert into app_user (username, password, first_name, last_name, birthday, hireday, salary, role, email, gender, project_id) values ('mrice8', 'tmAzpQ', 'Martin', 'Rice', '1983/07/17', '2010/12/27', 15508, 'EMPLOYEE', 'mrice8@php.net', 'MALE', 2);

insert into app_user (username, password, first_name, last_name, birthday, hireday, salary, role, email, gender, project_id) values ('nfrazier9', 'oIYRGCqbfo', 'Nicole', 'Frazier', '1983/09/26', '2007/08/16', 32685, 'EMPLOYEE', 'nfrazier9@mapquest.com', 'FEMALE', 3);
insert into app_user (username, password, first_name, last_name, birthday, hireday, salary, role, email, gender, project_id) values ('jjordana', 'C1rsRzR9', 'Jimmy', 'Jordan', '1980/05/29', '2014/11/09', 24680, 'EMPLOYEE', 'jjordana@hao123.com', 'MALE', 3);

insert into app_user (username, password, first_name, last_name, birthday, hireday, salary, role, email, gender) values ('akingb', 'sT2BSjrKd', 'Aaron', 'King', '1981/04/29', '2015/04/13', 18418, 'EMPLOYEE', 'akingb@meetup.com', 'MALE');
insert into app_user (username, password, first_name, last_name, birthday, hireday, salary, role, email, gender) values ('cgarrettu', '126oyJB6q', 'Charles', 'Garrett', '1988/04/26', '2015/11/21', 79936, 'EMPLOYEE', 'cgarrettu@marketwatch.com', 'FEMALE');
insert into app_user (username, password, first_name, last_name, birthday, hireday, salary, role, email, gender) values ('shicksv', 'AlpFlX0xx9fl', 'Sandra', 'Hicks', '1984/01/18', '2010/10/16', 50808, 'EMPLOYEE', 'shicksv@biblegateway.com', 'MALE');
insert into app_user (username, password, first_name, last_name, birthday, hireday, salary, role, email, gender) values ('gmorenow', '7lxpV4gPJ2Xe', 'Gloria', 'Moreno', '1980/07/01', '2007/06/12', 62224, 'EMPLOYEE', 'gmorenow@zimbio.com', 'MALE');

INSERT INTO app_user (username, password, first_name, last_name, birthday, hireday, salary, role, email, gender) VALUES ('sbutler2', 'gmGVqKeT', 'Stephen', 'Butler', '1975/08/22', '2015/12/29', 30412, 'PM', 'sbutler2@discuz.net', 'MALE');
INSERT INTO app_user (username, password, first_name, last_name, birthday, hireday, salary, role, email, gender) VALUES ('mrodriguez7', 't3TsZbScr', 'Marilyn', 'Rodriguez', '1977/06/29', '2015/07/08', 34384, 'PM', 'mrodriguez7@liveinternet.ru', 'FEMALE');