INSERT INTO project(id, name, status) VALUES (1, 'Impleme', 'CREATED');
INSERT INTO project(id, name, status) VALUES (2, 'Threddy', 'CREATED');
INSERT INTO project(id, name, startdate, status) VALUES (3, 'Minerva', '2016-08-20', 'IN_PROGRESS');
INSERT INTO project(id, name, startdate, status) VALUES (4, 'Flangex', '2016-10-12', 'IN_PROGRESS');
INSERT INTO project(id, name, startdate, status) VALUES (5, 'Tesla', '1995-07-12', 'IN_PROGRESS');
INSERT INTO project(id, name, startdate, status) VALUES (6, 'Kaler', '2015-12-17', 'IN_PROGRESS');
INSERT INTO project(id, name, startdate, status) VALUES (7, 'CoveBox', '2016-04-30', 'IN_PROGRESS');
INSERT INTO project(id, name, startdate, status) VALUES (8, 'Sugger', '2016-09-09', 'IN_PROGRESS');
INSERT INTO project(id, name, startdate, status) VALUES (9, 'Deton', '2016-01-21', 'IN_PROGRESS');
INSERT INTO project(id, name, startdate, status) VALUES (10, 'Mobili', '2016-03-11', 'IN_PROGRESS');
INSERT INTO project(id, name, startdate, status) VALUES (11, 'ExtJSLinq', '2016-02-14', 'IN_PROGRESS');
INSERT INTO project(id, name, startdate, status) VALUES (12, 'Websheling', '2016-02-17', 'IN_PROGRESS');
INSERT INTO project(id, name, startdate, enddate, status) VALUES (13, 'Aidogo', '2010-06-06', '2012-08-20', 'CLOSED');
INSERT INTO project(id, name, startdate, enddate, status) VALUES (14, 'Titartalk', '2010-01-23', '2013-10-19', 'CLOSED');
INSERT INTO project(id, name, startdate, enddate, status) VALUES (15, 'Rivecore', '2010-01-18', '2014-11-29', 'CLOSED');